### ISSUE TITLE
write an ontology for sharks

### ISSUE THREAD

**Issue by mcodescu** [ConceptualBlending/conceptual_blending_project#28]

**Comment by SillyCodeValley** [comment]
please put your ontology file in "animal_ontologies" directory

**Comment by Sriram308** [comment]
conceptual_blending_project/animal_ontologies/shark.dol

**Comment by mcodescu** [comment]
Can you rename the class Trunk to SharkTrunk?

**Comment by Sriram308** [comment]
conceptual_blending_project/animal_ontologies/shark.dol
