### ISSUE TITLE
make sure that pretty printing is valid Manchester Syntax

### ISSUE THREAD

**Issue by mcodescu** [ConceptualBlending/conceptual_blending_project#35]

**Comment by fabianneuhaus** [comment]
Example where it is not valide manchester syntax :
Pretty printer puts out
Class:Birds
EquivalentTo:Class:Animal

Valid syntax is:
Class: Birds
EquivalentTo: Animal 

Note white spaces and missing second occurrence of "Class:"

**Comment by Sriram308** [comment]
conceptual_blending_project/Exercise/write_ontologies/Sriram/valid manchester syntax.rb
